const CONSTANTS = {
  DATA_FETCHING: 'DATA_FETCHING',
  DATA_RECEIVED: 'DATA_RECEIVED',
  USER_SIGNED_IN: 'USER_SIGNED_IN',
  CURRENT_USER: 'CURRENT_USER',
  USER_SIGNED_OUT: 'USER_SIGNED_OUT',
  ERROR_SESSIONS: 'ERROR_SESSIONS',
  ERROR_REGISTRATIONS: 'ERROR_REGISTRATIONS',
  NOTEPADS_FETCHING: 'NOTEPADS_FETCHING',
  NOTEPADS_RECEIVED: 'NOTEPADS_RECEIVED',
  NOTEPADS_CREATING: 'NOTEPADS_CREATING',
  NOTEPADS_CREATED: 'NOTEPADS_CREATED',
  NOTEPADS_CREATE_ERROR: 'NOTEPADS_CREATE_ERROR',
  NOTEPADS_SAVE_ERROR: 'NOTEPADS_SAVE_ERROR',
  NOTEPADS_ERRORS: 'NOTEPADS_ERRORS',
  NOTEPADS_OWNED_DELETE: 'NOTEPADS_OWNED_DELETE',
  NOTEPADS_OWNED_SAVE: 'NOTEPADS_OWNED_SAVE',
  NOTEPADS_SHARED_DELETE: 'NOTEPADS_SHARED_DELETE',
  NOTEPAD_ACTIVATE: 'NOTEPAD_ACTIVATE',
}

export default CONSTANTS
